name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Запускати тільки при оновленні головної гілки

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Дозвіл на запис у реєстр GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Токен генерується автоматично, нічого налаштовувати не треба

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Заміни "thesis-i/department-web-front-end" на точну назву вашої організації та репозиторію (все маленькими літерами)
          tags: ghcr.io/nulp-ai-enterprise/landing:latest
